---
    name: Checks

    on: [push]

    jobs:
      test-lint:
        name: Test and Lint
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v2
          - name: Setup Python
            uses: actions/setup-python@v2
          - name: Install requirements
            run: |
                pip install -r requirements.txt
          - name: Test
            run: |
                cd post_app_api
                python manage.py test
          - name: Lint
            run: |
                cd post_app_api
                flake8